### ISSUE TITLE
No justifications around any timeframes

### ISSUE THREAD

**Issue by Cookizza** [davebs/AgileLite#11]
I'm trying to understand how this is a strategy and not an alternative rambling from someone who feels overworked or over tasked.

- Why 3 week sprints? 

- Why an entire week off for  a 45 minute meeting

- Why are tickets that are not complete in a sprint then backlogged instead of being completed in the week off? Surely if a sprint is well planned then developers are not burnt out when they still have incomplete items?

How has this ramble got 900 stars already?

Please provide an ounce of justification and/or proof to these timeframes.

**Comment by davebs** [comment]
I added an faq that will hopefully answer some of your questions and others.

> Why 3 week sprints?

Because development work plus recovery time then fits into 12 slots per year. When the month is over, a new month begins. The "week off" allows a reset, and a new sprint begins. It's about achieving a cadence and having clear and consistent intervals.

> Can we do a kanban style rolling iteration where start dates and end dates vary and depend on circumstances?

I really value the concept of the work month having a defined start and stop and that month being defined by a single block of tasks. Rolling iterations not synced to months would mess that up.

> Does it really take a week to plan a sprint?

No, that's the point. It's a light week.
