### ISSUE TITLE
Why 3 weeks sprints?

### ISSUE THREAD

**Issue by togadera** [davebs/AgileLite#9]
Could you elaborate on why 3 weeks is a good time? What would happen if teams increased or decreased the time period. In my experience 3 weeks to far too long and leads to staled issues and extra stress near the end.

**Comment by davebs** [comment]
Hello, I added an FAQ that attempts to answer some of these questions and others:

> Why 3 week sprints?

Because development work plus recovery time then fits into 12 slots per year. When the month is over, a new month begins. The "week off" allows a reset, and a new sprint begins. It's about achieving a cadence and having clear and consistent intervals.

> Can we do a kanban style rolling iteration where start dates and end dates vary and depend on circumstances?

I really value the concept of the work month having a defined start and stop and that month being defined by a single block of tasks. Rolling iterations not synced to months would mess that up.

---

It's a fair point about them being too long, I know what you mean. I think 1 week is too short, 2 might be ok, but I kind of prefer 3. 

As I've gone through the FAQ, I'm finding points that are flexible versus not as far as I've defined "Agile Lite". For instance, how "off" your "off week" is is flexible--do what's comfortable. But the 3 week thing and monthly cadence strike me as fairly important.
